# Generated by Django 5.0.6 on 2024-06-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default='2000-01-01', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img_user/desarrollador-ejemplo.svg', upload_to='img_user/', verbose_name='Photo'),
        ),
    ]
