# Generated by Django 5.0.6 on 2024-06-13 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_author_book_author_alter_book_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_book',
            field=models.FileField(default='', upload_to='img_books', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='gender',
            field=models.CharField(choices=[('ACN', 'Accion'), ('ATR', 'Adventure'), ('CMD', 'Comedy'), ('RMC', 'Romance'), ('CRM', 'Crime'), ('ANMT', 'Animation')], default='', max_length=4),
        ),
    ]
