# Generated by Django 5.0.6 on 2024-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img_book',
            field=models.ImageField(default='', upload_to='img_books/', verbose_name='Image'),
        ),
    ]
