# Generated by Django 5.0.6 on 2024-06-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_book_img_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img_book',
            field=models.ImageField(default='img_books/hero-inferior.svg', upload_to='img_books/', verbose_name='Image'),
        ),
    ]
